class_name StationArt

## Which picture a station (or the NC shelf) shows on the floor and in the
## menus. Two complete sets, switched in Settings (ThemeManager.station_art):
##   PIXEL - hand-built 48x48 8-bit sprites, assets/sprites/stations_pixel/
##           (generated by tools/gen_station_pixel_art.py)
##   AI    - the AI-generated set, cropped to 384px, assets/sprites/stations_ai/
## Both name files by station id ("printing" covers every printer instance);
## "<id>_running.png", where present, is shown while the machine runs.

const DIRS := {
	ThemeManager.StationArtStyle.PIXEL: "res://assets/sprites/stations_pixel/",
	ThemeManager.StationArtStyle.AI: "res://assets/sprites/stations_ai/",
}

static var _cache: Dictionary = {}


static func art_id(station_id: String) -> String:
	return "printing" if station_id.begins_with("printing") else station_id


static func texture_for(station_id: String, running: bool = false) -> Texture2D:
	var dir: String = DIRS[ThemeManager.station_art]
	var id := art_id(station_id)
	if running:
		var lit := _load(dir + id + "_running.png")
		if lit != null:
			return lit
	return _load(dir + id + ".png")


## Pixel art is drawn with nearest filtering; the AI set is a downscaled
## painting, so it reads better filtered.
static func texture_filter() -> CanvasItem.TextureFilter:
	if ThemeManager.station_art == ThemeManager.StationArtStyle.PIXEL:
		return CanvasItem.TEXTURE_FILTER_NEAREST_WITH_MIPMAPS
	return CanvasItem.TEXTURE_FILTER_LINEAR_WITH_MIPMAPS


static func _load(path: String) -> Texture2D:
	if not _cache.has(path):
		_cache[path] = load(path) if ResourceLoader.exists(path) else null
	return _cache[path]
