class_name UiIcons

## Placeholder 16x16 pixel-art HUD icons, drawn from ASCII grids at runtime
## (design doc Section 27.5: no UI icon art exists yet). Swap any of these
## for a real texture later by changing get_icon() - nothing else reads the
## grids. One char per pixel; see PALETTE for the legend, "." = transparent.

const PALETTE := {
	"k": Color(0.07, 0.06, 0.05), # outline
	"w": Color(0.95, 0.92, 0.85), # off-white
	"g": Color(0.92, 0.70, 0.20), # gold
	"o": Color(0.90, 0.42, 0.15), # ember
	"s": Color(0.62, 0.65, 0.70), # steel
	"d": Color(0.22, 0.24, 0.28), # dark steel
	"b": Color(0.45, 0.78, 0.96), # gem blue
	"n": Color(0.35, 0.80, 0.35), # green
	"r": Color(0.86, 0.26, 0.22), # red
	"y": Color(1.00, 0.84, 0.32), # yellow
	"c": Color(0.45, 0.86, 0.95), # cyan
	"t": Color(0.93, 0.76, 0.60), # skin
	"u": Color(0.52, 0.34, 0.18), # brown
	"l": Color(0.84, 0.86, 0.90), # light steel
}

const GRIDS := {
	"contracts": [
		"................",
		"...kkkkkkkkk....",
		"...kwwwwwwwkk...",
		"...kwkkkkkwwkk..",
		"...kwwwwwwwwwk..",
		"...kwkkkkkkkwk..",
		"...kwwwwwwwwwk..",
		"...kwkkkkkkkwk..",
		"...kwwwwwwwwwk..",
		"...kwkkkkwwwwk..",
		"...kwwwwwwggwk..",
		"...kwwwwwgoogk..",
		"...kwwwwwwggwk..",
		"...kwwwwwwwwwk..",
		"...kkkkkkkkkkk..",
		"................",
	],
	"dashboard": [
		"................",
		".kkkkkkkkkkkkkk.",
		".kssssssssssssk.",
		".ksddddddddddsk.",
		".ksddddddddgdsk.",
		".ksdddddddgddsk.",
		".ksdgdddddgddsk.",
		".ksddgdddgdddsk.",
		".ksdddgdgddddsk.",
		".ksddddgdddddsk.",
		".ksddddddddddsk.",
		".kssssssssssssk.",
		".kkkkkkkkkkkkkk.",
		"......kssk......",
		"....kkkkkkkk....",
		"................",
	],
	"overview": [
		"................",
		"................",
		"...........kkk..",
		"...........kgk..",
		".......kkk.kgk..",
		".......kgk.kgk..",
		".......kgk.kgk..",
		"...kkk.kgk.kgk..",
		"...kgk.kgk.kgk..",
		"...kgk.kgk.kgk..",
		"...kgk.kgk.kgk..",
		"...kgk.kgk.kgk..",
		".kkkkkkkkkkkkkk.",
		".kwwwwwwwwwwwwk.",
		".kkkkkkkkkkkkkk.",
		"................",
	],
	"staff": [
		"................",
		".....kkkkkk.....",
		"....kggggggk....",
		"...kggggggggk...",
		"..kkkkkkkkkkkk..",
		"..kggggggggggk..",
		"...kkkkkkkkkk...",
		"....kwwwwwwk....",
		"....kwkwwkwk....",
		"....kwwwwwwk....",
		".....kwwwwk.....",
		"...kkkkkkkkkk...",
		"..kssssssssssk..",
		"..kssssggssssk..",
		"..kssssssssssk..",
		"..kkkkkkkkkkkk..",
	],
	"transfer": [
		"................",
		".........k......",
		".........kk.....",
		".kkkkkkkkkgk....",
		".kggggggggggk...",
		".kkkkkkkkkgk....",
		".........kk.....",
		".........k......",
		"......k.........",
		".....kk.........",
		"....kokkkkkkkkk.",
		"...koooooooooook",
		"....kokkkkkkkkk.",
		".....kk.........",
		"......k.........",
		"................",
	],
	"printers": [
		"................",
		"..kkkkkkkkkkkk..",
		"..kssssssssssk..",
		"..kskkkkkkkksk..",
		"..kskwwwwwwksk..",
		"..kskwwoowwksk..",
		"..kskwwoowwksk..",
		"..kskwoooowksk..",
		"..kskkkkkkkksk..",
		"..kssssssssssk..",
		"..ksggsssssssk..",
		"..kssssssssssk..",
		"..kkkkkkkkkkkk..",
		"...kk......kk...",
		"................",
		"................",
	],
	"settings": [
		"................",
		"......kkkk......",
		"...kk.kssk.kk...",
		"..kssksssskssk..",
		"..kssssssssssk..",
		"...ksssddsssk...",
		".kkssdkkkkdsskk.",
		".kssskk..kksssk.",
		".kssskk..kksssk.",
		".kkssdkkkkdsskk.",
		"...ksssddsssk...",
		"..kssssssssssk..",
		"..kssksssskssk..",
		"...kk.kssk.kk...",
		"......kkkk......",
		"................",
	],
	"gold": [
		"................",
		"................",
		".....kkkkkk.....",
		"....kggggggk....",
		"...kgwwggggok...",
		"..kgwggggggggk..",
		"..kgwggkkgggok..",
		"..kgggkggkggok..",
		"..kgggkggkggok..",
		"..kggggkkgggok..",
		"..kgggggggggok..",
		"...kggggggook...",
		"....koooooook...",
		".....kkkkkkk....",
		"................",
		"................",
	],
	"gems": [
		"................",
		"................",
		"................",
		"....kkkkkkkk....",
		"...kbbwbbbbbk...",
		"..kbwbbbbbbbbk..",
		".kkkkkkkkkkkkkk.",
		"..kbbbbbbbbbbk..",
		"...kbbbbbbbbk...",
		"....kbbbbbbk....",
		".....kbbbbk.....",
		"......kbbk......",
		".......kk.......",
		"................",
		"................",
		"................",
	],
	"reputation": [
		"................",
		".......kk.......",
		"......kggk......",
		"......kggk......",
		".....kgwggk.....",
		"kkkkkkgwgggkkkkk",
		"kgggggwgggggggok",
		".kggggggggggook.",
		"..kggggggggook..",
		"...kgggggggok...",
		"...kgggkkggok...",
		"..kgggk..kgook..",
		"..kggk....kgok..",
		".kgkk......kkok.",
		".kk..........kk.",
		"................",
	],
	"attention": [
		"................",
		".....kkkkkk.....",
		"...kkkooookkk...",
		"..kkooowwoookk..",
		"..koooowwooook..",
		".kkoooowwooookk.",
		".kooooowwoooook.",
		".kooooowwoooook.",
		".kooooowwoooook.",
		".kooooowwoooook.",
		".kkooooooooookk.",
		"..koooowwooook..",
		"..kkooowwoookk..",
		"...kkkooookkk...",
		".....kkkkkk.....",
		"................",
	],
	"admin": [
		"................",
		"..........kkk...",
		".........kssk...",
		"........ksskk.k.",
		"........kssk.ksk",
		"........ksssksk.",
		".......kssssssk.",
		"......ksssskkk..",
		".....ksssk......",
		"....ksssk.......",
		"...ksssk........",
		"..ksssk.........",
		".ksssk..........",
		".kssk...........",
		"..kk............",
		"................",
	],
	"badge_ready": [
		"................",
		".....kkkkkk.....",
		"...kkknnnnkkk...",
		"..kknnnnnnnnkk..",
		"..knnnnnnnnnnk..",
		".kknnnnnnnnnnkk.",
		".knnnnnnnnnnwnk.",
		".knnnnnnnnnwnnk.",
		".knnwnnnnnwwnnk.",
		".knnwwnnnwwnnnk.",
		".kknnwwnwwnnnkk.",
		"..knnnwwwnnnnk..",
		"..kknnnwnnnnkk..",
		"...kkknnnnkkk...",
		".....kkkkkk.....",
		"................",
	],
	"badge_running": [
		".......kk.......",
		"...k..kggk..k...",
		"..kgk.kggk.kgk..",
		".kgggkggggkgggk.",
		"..kggggggggggk..",
		"...kggggggggk...",
		".kkgggkkkkgggkk.",
		"kgggggkkkkgggggk",
		"kgggggkkkkgggggk",
		".kkgggkkkkgggkk.",
		"...kggggggggk...",
		"..kggggggggggk..",
		".kgggkggggkgggk.",
		"..kgk.kggk.kgk..",
		"...k..kggk..k...",
		".......kk.......",
	],
	"room_print": [
		"................",
		"..kkkkkkkkkkkk..",
		"..kssssssssssk..",
		"..kskkkkkkkksk..",
		"..kskbbbbbbksk..",
		"..kskbwbbbbksk..",
		"..kskbbbbbbksk..",
		"..kskkkkkkkksk..",
		"..kssssssssssk..",
		"..ksssssssggsk..",
		"..kssssssssssk..",
		"..kkkkkkkkkkkk..",
		"...kk......kk...",
		"................",
		"................",
		"................",
	],
	"room_shell": [
		"................",
		"................",
		"....kkkkkkkk....",
		"...kwwwwwwwwk...",
		"..kwlllllllllk..",
		"..kllllllllllk..",
		"..kssssssssssk..",
		"..kslllllllllk..",
		"..kssssssssssk..",
		"..kslllllllllk..",
		"..kssssssssssk..",
		"...kssssssssk...",
		"....kkkkkkkk....",
		"................",
		"................",
		"................",
	],
	"room_furnace": [
		"................",
		".......kk.......",
		"......kook......",
		".....koook......",
		".....koyok......",
		"....koyyok.k....",
		"...kkoyyookok...",
		"...koyyyyooook..",
		"..koyyywyyoook..",
		"..koyywwwyyook..",
		"..koyywwwyyook..",
		"..kooyywyyoook..",
		"...kooyyyooook..",
		"....kooooook....",
		".....kkkkkk.....",
		"................",
	],
	"room_vim": [
		"................",
		".....kkkkkk.....",
		"....kssssssk....",
		"...ksoooooosk...",
		"...ksoyyyyosk...",
		"..kksoyyyyoskk..",
		"..kssooooooossk.",
		"..kssssssssssk..",
		"..ksddsddsddsk..",
		"..kssssssssssk..",
		"..ksddsddsddsk..",
		"..kssssssssssk..",
		"...ksssssssk....",
		"....kkkkkkk.....",
		"................",
		"................",
	],
	"room_post": [
		"................",
		".......k........",
		"......kyk.......",
		"......kyk.......",
		"..kk.kkykk.kk...",
		"..kykyyyyykyk...",
		"...kyywwyyk.....",
		"..kkyywwyykk....",
		".kyyyyyyyyyyk...",
		"..kkyywwyykk....",
		"...kyyyyyyk.....",
		"..kykkkykkkyk...",
		"..kk..kyk..kk...",
		"......kyk.......",
		".......k........",
		"................",
	],
	"act_upgrade": [
		"................",
		".......kk.......",
		"......kyyk......",
		".....kyyyyk.....",
		"....kyyyyyyk....",
		"...kyyyyyyyyk...",
		"..kkkkyyyykkkk..",
		".....kyyyyk.....",
		".....kyyyyk.....",
		".....kyyyyk.....",
		".....kyyyyk.....",
		".....kyyyyk.....",
		".....kkkkkk.....",
		"................",
		"................",
		"................",
	],
	"act_start": [
		"................",
		"....kk..........",
		"....kwkk........",
		"....kwwwkk......",
		"....kwwwwwkk....",
		"....kwwwwwwwkk..",
		"....kwwwwwwwwwk.",
		"....kwwwwwwwwwk.",
		"....kwwwwwwwkk..",
		"....kwwwwwkk....",
		"....kwwwkk......",
		"....kwkk........",
		"....kk..........",
		"................",
		"................",
		"................",
	],
	"act_collect": [
		"................",
		"................",
		"...kkkkkkkkkk...",
		"..kuuuuuuuuuuk..",
		"..kuuuyyuuuuuk..",
		"..kkkkkkkkkkkk..",
		"..kuuuuuuuuuuk..",
		"..kuuuuuuuuuuk..",
		"..kuukkkkkkuuk..",
		"..kuuuuuuuuuuk..",
		"..kuuuuuuuuuuk..",
		"..kuuuuuuuuuuk..",
		"..kkkkkkkkkkkk..",
		"................",
		"................",
		"................",
	],
	"act_queue": [
		"................",
		"................",
		"..kkk.kkkkkkkk..",
		"..kwk.kwwwwwwk..",
		"..kkk.kkkkkkkk..",
		"................",
		"..kkk.kkkkkkkk..",
		"..kwk.kwwwwwwk..",
		"..kkk.kkkkkkkk..",
		"................",
		"..kkk.kkkkkkkk..",
		"..kwk.kwwwwwwk..",
		"..kkk.kkkkkkkk..",
		"................",
		"................",
		"................",
	],
	"act_rack": [
		"................",
		"..kkkkkkkkkkkk..",
		"..kssssssssssk..",
		"..ksdddsddddsk..",
		"..ksdgdsdgddsk..",
		"..kssssssssssk..",
		"..ksdddsddddsk..",
		"..ksdgdsddddsk..",
		"..kssssssssssk..",
		"..ksdddsddddsk..",
		"..ksddddsdgdsk..",
		"..kssssssssssk..",
		"..kkkkkkkkkkkk..",
		"................",
		"................",
		"................",
	],
	"act_send": [
		"................",
		"................",
		"........kk......",
		"........kwk.....",
		"..kkkkkkkwwk....",
		"..kwwwwwwwwwk...",
		"..kwwwwwwwwwwk..",
		"..kwwwwwwwwwk...",
		"..kkkkkkkwwk....",
		"........kwk.....",
		"........kk......",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"act_scrap": [
		"................",
		"......kkkk......",
		"..kkkkkwwkkkkk..",
		"..kwwwwwwwwwwk..",
		"..kkkkkkkkkkkk..",
		"...kssssssssk...",
		"...ksdsdsdsdsk..",
		"...ksdsdsdsdk...",
		"...ksdsdsdsdk...",
		"...ksdsdsdsdk...",
		"...ksdsdsdsdk...",
		"...ksssssssk....",
		"....kkkkkkk.....",
		"................",
		"................",
		"................",
	],
	"act_rework": [
		"................",
		"......kkkk......",
		"......kwwk......",
		"......kwwk......",
		".....kwwwwk.....",
		"....kwwwwwwk....",
		"...kwwwwwwwwk...",
		"...kccccccccck..",
		"..kccwcccccccck.",
		"..kcccccccwccck.",
		"..kccccccccccck.",
		"...kkkkkkkkkkk..",
		"................",
		"................",
		"................",
		"................",
	],
	"act_scan": [
		"................",
		"....kkkkk.......",
		"...kccccck......",
		"..kcwwcccck.....",
		"..kcwccccck.....",
		"..kccccccck.....",
		"..kccccccck.....",
		"...kcccccdk.....",
		"....kkkkkddk....",
		"..........kddk..",
		"...........kddk.",
		"............kdk.",
		".............k..",
		"................",
		"................",
		"................",
	],
	"act_lock": [
		"................",
		".....kkkkk......",
		"....kdddddk.....",
		"...kdk...kdk....",
		"...kdk...kdk....",
		"..kkkkkkkkkkk...",
		"..kgggggggggk...",
		"..kggggkggggk...",
		"..kgggkkkgggk...",
		"..kggggkggggk...",
		"..kgggggggggk...",
		"..kkkkkkkkkkk...",
		"................",
		"................",
		"................",
		"................",
	],
	"act_refresh": [
		"................",
		".....kkkkk......",
		"...kkcccccckk...",
		"..kcck....kcck..",
		"..kck......kck..",
		"..kck.....kkckk.",
		"..kck......ccc..",
		"..kkk.......c...",
		"...c........kkk.",
		"..ccc......kck..",
		".kkckk.....kck..",
		"..kck......kck..",
		"..kcck....kcck..",
		"...kkcccccckk...",
		"......kkkkk.....",
		"................",
	],
	"act_hire": [
		"................",
		".....kkkk.......",
		"....kttttk......",
		"....kttttk......",
		"....kttttk..kk..",
		".....kkkk..knk..",
		"...kkbbbbkkknkk.",
		"..kbbbbbbbknnnk.",
		"..kbbbbbbbbknk..",
		"..kbbbbbbbbbkk..",
		"..kbbbbbbbbbk...",
		"..kkkkkkkkkkk...",
		"................",
		"................",
		"................",
		"................",
	],
	"st_warning": [
		"................",
		".......kk.......",
		"......kyyk......",
		"......kyyk......",
		".....kyyyyk.....",
		".....kykkyk.....",
		"....kyykkyyk....",
		"....kyykkyyk....",
		"...kyyykkyyyk...",
		"...kyyyyyyyyk...",
		"..kyyyykkyyyyk..",
		"..kyyyykkyyyyk..",
		".kyyyyyyyyyyyyk.",
		".kkkkkkkkkkkkkk.",
		"................",
		"................",
	],
	"st_hourglass": [
		"................",
		"...kkkkkkkkkk...",
		"...kuuuuuuuuk...",
		"....kwwwwwwk....",
		"....kwyyyywk....",
		".....kwyywk.....",
		"......kyyk......",
		"......kwwk......",
		".....kwwywk.....",
		"....kwwyywwk....",
		"....kwyyyywk....",
		"...kuuuuuuuuk...",
		"...kkkkkkkkkk...",
		"................",
		"................",
		"................",
	],
	"st_clock": [
		"................",
		".....kkkkkk.....",
		"...kkwwwwwwkk...",
		"..kwwwwkwwwwwk..",
		"..kwwwwkwwwwwk..",
		".kwwwwwkwwwwwwk.",
		".kwwwwwkwwwwwwk.",
		".kwwwwwkkkkkwwk.",
		".kwwwwwwwwwwwwk.",
		".kwwwwwwwwwwwwk.",
		"..kwwwwwwwwwwk..",
		"..kwwwwwwwwwwk..",
		"...kkwwwwwwkk...",
		".....kkkkkk.....",
		"................",
		"................",
	],
	"st_info": [
		"................",
		".....kkkkkk.....",
		"...kkbbbbbbkk...",
		"..kbbbbwwbbbbk..",
		"..kbbbbwwbbbbk..",
		".kbbbbbbbbbbbbk.",
		".kbbbbwwwbbbbbk.",
		".kbbbbbwwbbbbbk.",
		".kbbbbbwwbbbbbk.",
		".kbbbbbwwbbbbbk.",
		"..kbbbwwwwbbbk..",
		"..kbbbbbbbbbbk..",
		"...kkbbbbbbkk...",
		".....kkkkkk.....",
		"................",
		"................",
	],
	"st_check": [
		"................",
		"................",
		"..............k.",
		".............knk",
		"............knnk",
		"...........knnk.",
		"..k.......knnk..",
		".knk.....knnk...",
		".knnk...knnk....",
		"..knnk.knnk.....",
		"...knnknnk......",
		"....knnnk.......",
		".....knk........",
		"......k.........",
		"................",
		"................",
	],
	"st_cross": [
		"................",
		"................",
		"..kk........kk..",
		"..krk......krk..",
		"...krk....krk...",
		"....krk..krk....",
		".....krkkrk.....",
		"......krrk......",
		"......krrk......",
		".....krkkrk.....",
		"....krk..krk....",
		"...krk....krk...",
		"..krk......krk..",
		"..kk........kk..",
		"................",
		"................",
	],
	"role_technician": [
		"................",
		"..........kk....",
		".........kssk...",
		"........kssk....",
		"...k...kssk.....",
		"..ksk.kssk......",
		"..ksskssk.......",
		"...ksssk........",
		"....ksssk.......",
		"...kssk.kk......",
		"..kssk..........",
		".kssk...........",
		".ksk............",
		"..k.............",
		"................",
		"................",
	],
	"role_engineer": [
		"................",
		"......kkkk......",
		"...kk.kbbk.kk...",
		"..kbbkbbbbkbbk..",
		"..kbbbbbbbbbbk..",
		"...kbbbddbbbk...",
		".kkbbbdkkdbbbkk.",
		".kbbbbdkkdbbbbk.",
		".kbbbbdkkdbbbbk.",
		".kkbbbdkkdbbbkk.",
		"...kbbbddbbbk...",
		"..kbbbbbbbbbbk..",
		"..kbbkbbbbkbbk..",
		"...kk.kbbk.kk...",
		"......kkkk......",
		"................",
	],
	"part_turbine": [
		"................",
		"..........kk....",
		".........klsk...",
		"........klssk...",
		".......klssk....",
		"......klssk.....",
		".....klssk......",
		"....klssk.......",
		"...klssk........",
		"..kkkssk........",
		".kssssssk.......",
		".kddddddk.......",
		".kkkkkkkk.......",
		"................",
		"................",
		"................",
	],
	"part_valve": [
		"................",
		".......kk.......",
		"......kssk......",
		"....kkkssk......",
		"...kdddddkk.....",
		"..kkksssssskkk..",
		".klllssssslllk..",
		".kllsssssssllk..",
		".klllssssslllk..",
		"..kkksssssskkk..",
		"....kssssssk....",
		".....kkkkkk.....",
		"................",
		"................",
		"................",
		"................",
	],
	"part_bracket": [
		"................",
		"................",
		"..kkkk..........",
		"..klsk..........",
		"..klsk..........",
		"..klsk..........",
		"..klsk..........",
		"..klskkkkkkkkk..",
		"..kllllllllllsk.",
		"..klssssssssssk.",
		"..kkkkkkkkkkkkk.",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"part_housing": [
		"................",
		"...kkkkkkkkkk...",
		"..klllllllllsk..",
		"..klkkkkkkkksk..",
		"..klk......ksk..",
		"..klk......ksk..",
		"..klk......ksk..",
		"..klk......ksk..",
		"..klkkkkkkkksk..",
		"..klssssssssssk.",
		"..kkkkkkkkkkkkk.",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"part_ring": [
		"................",
		".....kkkkkk.....",
		"...kkllllllkk...",
		"..klllssssslsk..",
		"..klskkkkkkssk..",
		".klsk......kssk.",
		".klsk......kssk.",
		".klsk......kssk.",
		".klsk......kssk.",
		"..klskkkkkkssk..",
		"..klssssssssk...",
		"...kksssssskk...",
		".....kkkkkk.....",
		"................",
		"................",
		"................",
	],
	"part_impeller": [
		"................",
		".......kk.......",
		"...kk.klsk.kk...",
		"..klskklsk.ksk..",
		"...klskssk.kk...",
		"....klssssk.....",
		".kkkksdddskkkk..",
		".klsssdkkdsssk..",
		".kkkksdddskkkk..",
		"....kssssk......",
		"...kk.ksskssk...",
		"..kssk.ksk.ksk..",
		"...kk..kk...kk..",
		"................",
		"................",
		"................",
	],
	"part_shaft": [
		"................",
		"............kk..",
		"...........klsk.",
		"..........klsk..",
		".........klsk...",
		"........klsk....",
		".......klsk.....",
		"......klsk......",
		".....klsk.......",
		"....klsk........",
		"...klsk.........",
		"..klsk..........",
		".kssk...........",
		"..kk............",
		"................",
		"................",
	],
	"part_pendant": [
		"................",
		".......kk.......",
		"......kyyk......",
		".......kk.......",
		".....kkggkk.....",
		"....kggyyggk....",
		"...kgyyyyyygk...",
		"...kgyywyyygk...",
		"...kgyyyyyygk...",
		"....kggyyggk....",
		".....kkggkk.....",
		".......kk.......",
		"................",
		"................",
		"................",
		"................",
	],
	"factory": [
		"................",
		"..kkk...........",
		"..kok...........",
		"..kgk...........",
		"..kgk.k...k.....",
		"..kgkksk.ksk....",
		"..kgksssksssk...",
		".kkkkkkkkkkkkkk.",
		".kssssssssssssk.",
		".kswwsswwsswwsk.",
		".kswwsswwsswwsk.",
		".kssssssssssssk.",
		".kssssskkssssk..",
		".kssssskkssssk..",
		".kkkkkkkkkkkkk..",
		"................",
	],
}

static var _cache: Dictionary = {}


static func get_icon(icon_name: String) -> Texture2D:
	if _cache.has(icon_name):
		return _cache[icon_name]
	var grid: Array = GRIDS.get(icon_name, [])
	var image := Image.create(16, 16, false, Image.FORMAT_RGBA8)
	for y in range(mini(grid.size(), 16)):
		var row: String = grid[y]
		for x in range(mini(row.length(), 16)):
			var ch := row[x]
			if PALETTE.has(ch):
				image.set_pixel(x, y, PALETTE[ch])
	var texture := ImageTexture.create_from_image(image)
	_cache[icon_name] = texture
	return texture
